### ISSUE TITLE
Payment options not shown in German language

### ISSUE THREAD

**Issue by Fruitboompje** [mollie/PrestaShop1.7#514]
### Expected behavior
All payment options are enabled for all locales. 

### Actual behavior
For all languages the payment options are shown, except for the German language. Then only an empty `<div>` is rendered

### Steps to reproduce the behavior
Not sure, was working before... replacing old versions don't fix this problem

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.4.3
* PHP version: 7.2.34

**Comment by loonas** [comment]
Hi @Fruitboompje,

Thank you for reaching out to us, and thank you for bringing our attention to this issue.
In order to resolve this, could you please check in your BO->International->Localization if the language codes have this format?
![image](https://user-images.githubusercontent.com/30753843/150969604-ae2f8bea-3c05-4f35-a241-f481675a6697.png)
In case your shop already has the correct language codes, could you share your BO+FTP credentials to support@invertus.eu?

We would be more than happy to investigate this further with our developer.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Fruitboompje,

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

Best regards,
Invertus Support team
