### ISSUE TITLE
Payment fee not in order confirmation

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop1.7#518]
### Expected behavior
Payment fee displayed  in order confirmation page.

### Actual behavior
Not displayed.

### Steps to reproduce the behavior
Create order 
Pay the order with a payment fee

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 5.0.0
* PHP version: 7.3

**Comment by loonas** [comment]
Hi @basemedia! I hope that you are doing well!

Thank you for reaching out to us and your interest in perfecting the Mollie module.
Could you share screenshots of the place where the issue appears? It would help our developer to investigate.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by basemedia** [comment]
Payment Fee should be added to order-cofirmation.tpl page.

**Comment by loonas** [comment]
Hi @basemedia! How are you today?

Our team has looked into this request and at the moment, it is hard to implement due to Prestashop's logic with Payment Fees.
You can find a related issue right here: [Prestashop Github](https://github.com/PrestaShop/PrestaShop/issues/13170)

As it is difficult to achieve with the current Prestashop logic, currently I'm adding the to our wiki page named - [Upcoming fixes-Wishlist](https://github.com/mollie/PrestaShop1.7/wiki/Upcoming-fixes-Wishlist) and we will let you know once this feature is implemented.

For now, we will close the issue, but if you have any further questions, please do let us know!

Best regards,
Invertus Support team
