### ISSUE TITLE
Possibility to display Payment fee in checkout

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop1.7#519]
### Expected behavior
Payment fee displayed in shopping cart.

### Actual behavior
Not possible

### Steps to reproduce the behavior

see attached sreenshot. Display "transactie kosten" when payment method is selected with a payment fee (updated on the fly)

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 5.0.0
* PHP version: 7.1.26
<img width="791" alt="Screenshot 2022-01-27 at 14 22 37" src="https://user-images.githubusercontent.com/1645341/151367639-61629d0d-2287-45e7-954f-ad73e3a54b07.png">

**Comment by loonas** [comment]
Hi @basemedia!

Thank you for reaching out to us! I have forwarded the request to our team to check out and we will let you know once we have more details.

If you have any other questions in the meantime, let us know!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @basemedia! How are you today?

Our team has looked into this request and at the moment, it is hard to implement due to Prestashop's logic with Payment Fees.
You can find a related issue right here: [Prestashop Github](https://github.com/PrestaShop/PrestaShop/issues/13170)

As it is difficult to achieve with the current Prestashop logic, currently I'm adding the to our wiki page named - [Upcoming fixes-Wishlist](https://github.com/mollie/PrestaShop1.7/wiki/Upcoming-fixes-Wishlist) and we will let you know once this feature is implemented.

For now, we will close the issue, but if you have any further questions, please do let us know!

Best regards,
Invertus Support team

**Comment by Nathanpaternotte** [comment]
Hello,

Any news on this? It's a bit frustrating and counterintuitive to offer payment fee options if they are not displayed or added when placing an order...
