### ISSUE TITLE
Possibility to add tax to payment fee

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop1.7#520]
### Expected behavior
Possibility to add tax to payment fee

### Actual behavior
Not possible

### Steps to reproduce the behavior
Attached screenshot.

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 5..0.0 
* PHP version: 7.1.26 
![Screenshot 2022-01-28 at 13 22 04](https://user-images.githubusercontent.com/1645341/151546150-f73e5a91-5202-45fd-b02c-fb4f390310e4.png)

**Comment by basemedia** [comment]
The one euro is payment fee.

**Comment by loonas** [comment]
Hi @basemedia! Thank you for your inquiry!

I have forwarded it to the team to check out. We will let you know once we have any further information!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @basemedia! I hope you are well!

Our team has looked into this request and at the moment, it is hard to implement due to Prestashop's logic with Payment Fees.
You can find a related issue right here: [Prestashop Github](https://github.com/PrestaShop/PrestaShop/issues/13170)

As it is difficult to achieve with the current Prestashop logic, currently I'm adding the to our wiki page named - [Upcoming fixes-Wishlist](https://github.com/mollie/PrestaShop1.7/wiki/Upcoming-fixes-Wishlist) and we will let you know once this feature is implemented.

For now, we will close the issue, but if you have any further questions, please do let us know!

Best regards,
Invertus Support team
