### ISSUE TITLE
Slice it and Apple Pay does not show

### ISSUE THREAD

**Issue by RomanSRNWEB** [mollie/PrestaShop1.7#525]
### Expected behavior
For all payment methods selected in the module and on the Mollie website to work
### Actual behavior
Slice it and Apple Pay does not show in the shopping cart in payment methods
### Steps to reproduce the behavior
After updating the module, these payment methods do not show https://prnt.sc/26nv77m and https://prnt.sc/26nv7dz

### Environment
* PrestaShop version: 1.7.7.1 
* Mollie module version: v5.0.0
* PHP version: 7.1.26

**Comment by basemedia** [comment]
Did you test Apple Pay with an Iphone? Only shows up on an Iphone.

**Comment by RomanSRNWEB** [comment]
yes, just checked again
![file](https://user-images.githubusercontent.com/57991826/152344358-0f90f126-156d-4c1d-ac2d-2b0526edd594.jpg)

**Comment by loonas** [comment]
Hi there @RomanSRNWEB! I hope that you are doing well!

I have checked the details of the issue, and forwarded it to our developer. We will keep you updated regarding this issue and the progress.

Best regards,
Invertus Support team

**Comment by RomanSRNWEB** [comment]
Hi there @loonas.  I am fine. I hope that you are doing well too! Thanks for the quick response. For my part, I tried to remove, reset, reinstall the module. on module version 4.3.2, the payment method Slice it showed.
![image](https://user-images.githubusercontent.com/57991826/152347309-70c20fa2-170a-410a-b486-511d9b396ae0.png)

**Comment by loonas** [comment]
Thank you for your reply @RomanSRNWEB and the additional details!

Our developer has looked over the issue, and we were unable to replicate it on our side.

In order to resolve this issue, could you let us know what was the amount of the payment, where Slice it did not show in the checkout? Additionally, could you specify what country was selected for the billing address?

Slice it will only show as a payment method option in the checkout if the user is from Germany and is making a purchase of over 45 euros, or from Austria/Finland and is making a purchase of over 100 euros. You can find this information in [the Mollie page regarding the minimum and maximum amounts per payment method](https://help.mollie.com/hc/en-us/articles/115000667365-What-is-the-minimum-and-maximum-amount-per-payment-method-).

Additionally, regarding Apple Pay, please make sure that your Apple device has an active Apple Pay application, otherwise, the payment method will be hidden.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RomanSRNWEB** [comment]
@loonas 
thanks for the clarification. Slice it works correctly.
Apple Pay still does not work, I checked it on several phones (Apple device) and PC, Apple Pay application is active everywhere

**Comment by loonas** [comment]
Thank you for your reply @RomanSRNWEB!

I'm happy to hear that Slice it is working without any issues! Regarding Apple Pay, in order to check the issue further, could you share your BO credentials to support@invertus.eu?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @RomanSRNWEB! Hope that you are doing well.

Our developer has checked the issue with the provided details, but was unable to find something as he was unable to view the shop.
Could you share the link to the front office, so that we could view the shop and the issue through there?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RomanSRNWEB** [comment]
https://megafitstore.com/de/ a copy of the site  https://gofitness.ch/  ,
but  ( https://gofitness.ch/  ) there is an older version of the module and
Apple works, and the supercheckout module is also worth

пт, 18 февр. 2022 г. в 14:54, Augustė Balčiūnaitė ***@***.***

**Comment by loonas** [comment]
Thank you for your reply @RomanSRNWEB!

I see, thank you for the information. It could be due to different configurations on the copy site in the Supercheckout module, so we would recommend getting in touch with the developers of the Supercheckout module, as currently, our developer was able to see that the Apple Pay method is not showing due to the disturbances with loading JS, which comes directly from the Supercheckout module code files.

Let us know if you have any further questions!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @RomanSRNWEB! I hope that you are doing well.

Let us know once you're ready to continue with this or if you have any further questions!

For now, due inactivity, we will mark this issue as resolved.

Best regards,
Invertus Support team
