### ISSUE TITLE
PageSpeed Insights issues

### ISSUE THREAD

**Issue by Gozylatech** [mollie/PrestaShop1.7#527]
### Expected behavior
Reduce unused JavaScript, Enable Text Compression, Avoid serving legacy JavaScript to modern browsers

### Actual behavior
Slows down the website

### Steps to reproduce the behavior
Install Mollie

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: 4.4.3
* PHP version: 7.0

**Comment by loonas** [comment]
Hi there @Gozylatech! I hope that you are doing well.

Thank you for your feedback and your interest in perfecting the Mollie module. I noticed that you are using an outdated Mollie version, hence I would recommend updating the module to the latest one - 5.0.0-beta2 version. You can find it [here](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta2).

A lot of optimisation fixes have been implemented during this release, so the mentioned issues should no longer occur.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Gozylatech** [comment]
Hello, thank you for your answer. I tried to install it but the version remains on 4.4.3, is there a specific manipulation to do? Best regards

**Comment by loonas** [comment]
Thank you for your reply @Gozylatech!

We have checked with the team and noticed that you are using Prestashop 1.6, hence the newest Mollie version is not available.
We have added additional checks for the 5.0.0 release, so that only necessary JS would be loaded, which will greatly improve the performance - we would suggest upgrading to 1.7 if possible.

As for Prestashop 1.6, at the moment it is not possible to make any changes as they would interrupt the performance of the One page checkout.
Our developer has checked further for a good alternative, and it would be possible to add a custom validation in the store, that would improve the performance. 

In this case, could you specify if your shop has the default Prestashop checkout or some sort of one page checkout?

Looking forward to your reply!

Best regards,
Augustė

**Comment by Gozylatech** [comment]
Hello,

Thank you for your answer, our site does not use the one page checkout, it uses 5 steps Prestashop checkout.

Best regards

**Comment by loonas** [comment]
Thank you for your reply @Gozylatech!

I appreciate the information. We are reviewing the issue internally with our developer and we will let you know regarding the progress, and what possible solutions there could be.

As for 5.0.0 version of Mollie, it is only compatible with Prestashop 1.7 exclusively, and cannot be enabled on 1.6.1.24, which you are currently using.

We will keep you informed!

Best regards,
Augustė

**Comment by loonas** [comment]
Hi @Gozylatech! Hope that you are doing well.

Our developer has checked the issue, and specified how the module can be sped up with a simple addition to the hook, that would prevent loading JS and CSS, when it is not necessary.

You can apply it by adding this code to the **mollie.php** file, in the **hookActionFrontControllerSetMedia** function:
```
$isOrderController = $this->context->controller instanceof OrderControllerCore;
$isOPCController = $this->context->controller instanceof OrderOpcControllerCore;
if (!$isOPCController && !$isOrderController) {
   return;
}
```
![image](https://user-images.githubusercontent.com/30753843/153410262-9e86c05d-9674-4c9b-8c2c-441d807b8896.png)

As for further improvements, at the moment they are difficult to achieve, as making changes globally on the module can disrupt the performance of the One page checkout, that is being used on a lot of various shops. We are planning on working on them in more later future.

Let me know if you have any further questions, we are here for you!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @Gozylatech! I hope that you are doing well.

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

Best regards,
Invertus Support team
