### ISSUE TITLE
orders are being paid but not being created

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop1.7#547]
### Expected behavior
New order should be created after an succesfull payment.

### Actual behavior
New orders are not being created in Prestashop, the transaction is succesfull and showing in Mollie.

### Steps to reproduce the behavior
![Schermafbeelding 2022-03-03 094356](https://user-images.githubusercontent.com/49270150/156529308-675868a6-7ef5-4d2b-a3f7-4d6a8eea7d50.png)

### Environment
* PrestaShop version: 1.7.8.3
* Mollie module version: 5.0.1
* PHP version: 7.3.33

**Comment by loonas** [comment]
Hi @Maikel726,

Our developer has looked over the details, and it seems that the issue could be related to the webhook not being caught, or some misconfigurations.

In order to resolve the issue, could you please provide you BO+FTP details to support@invertus.eu? Additionally, did any errors appear in the mollie.com history?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Maikel726! Hope that you are doing well today.

Our developer has checked the issue and found that the order was not created, because the security key is not the same in Mollie meta_data and what we expect.
Could you let us know if this happens to all orders or just one? It seems that perhaps the order was created on an older Mollie version, and when it was completed, it was updated - on newest Mollie version the security key validation was changed.

If you wish to create this order, a fast temporary fix would be to add this line:

_if ($key !== $apiPayment->metadata->secure_key) {    break;}_

in src/transactionService.php : line 115, but only for this order and then call the Webhook again with this URL: https://www.autotravelshop.nl/module/mollie/webhook?id=tr_cMSuKFKz8g

Let us know if the issue persists and we will try further investigating why the security key is being generated differently in this shop!

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Maikel726,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions or if the issue occurs again!

Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

Where can i exactly find this file? the issue came back in another shop of me.

**Comment by Maikel726** [comment]
Hi @loonas I think i've found the file but the fix does not work. Should i send the credentials to ur developers?

**Comment by loonas** [comment]
Thank you for the update @Maikel726!

Yes, please share the BO+FTP credentials to [support@invertus.eu](mailto:support@invertus.eu), so that our team could check and investigate the issue further.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Maikel726,

Our developer has checked the details and had some additional questions. Could you share the order or payment ID from [Mollie – Effortless payments](http://mollie.com/)  for the order that failed to be created?

Our developer would be able to call Webhook with that ID and check if something is breaking. 
If the payment is using order API, then we need order ID; if it's payment API, then we need payment ID.

Additionally, a screenshot from Mollie.com history would be helpful, as we would be able to check if it had any errors or if Webhook was even called from Mollie.com.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

The payment ID is "tr_58JuKNEh9z" there are no errors in the webhook history.

![afbeelding](https://user-images.githubusercontent.com/49270150/159447745-ea28d1b1-008a-4114-aa3a-69d79f5d931d.png)

Please let me know if you need additional information.

**Comment by loonas** [comment]
Thank you for the information @Maikel726!

Our developer will look into it and we will let you know as soon as we have any news.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Maikel726! Hope that you are doing well today.

Our developer has checked the issue, and found out that the order is not created because security key is wrong. After debugging why the key might be wrong, the developer found out that the cart has no customer ID and no security key inside it. 

It seems that other modules or theme have some custom logic, that creates this issue. For the security, we need to generate keys using cart security key, customer ID, and module name. Right now it looks like before Mollie payment it had the customer ID and key, and one key was generated, but when we check in the Webhook and try to re-create the key, it is not the same, because the cart is missing customer information.

Here is the code snippet of how the cart is being checked when creating the order - as you can see the ID, customer ID and security key:
![image](https://user-images.githubusercontent.com/30753843/160363193-fa98dee5-e602-4485-b640-ff682c17c457.png)

Could you possibly share more details on why is the cart like this? It seems that some other modules or theme are altering it.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Thank you for your reply @Maikel726,

In this case, we would recommend checking your active modules or theme, that could affect the cart ID, or customer ID. As the issue is related to a third-party module, we are unable to check the issue further as it is out of the Mollie scope. 

In case the issue appears again, please do let us know and we will be able to investigate it further.

Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hi @Maikel726,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions or if the issue occurs again!

Best regards,
Invertus Support team

**Comment by alohaoanna** [comment]
Hi @loonas 

we have the same problem with some orders. We can find a lot of order with "paid" status but without order created.

Could you check these 2 payment IDs to see if the problem is the secure key ? We need to fix it but we don't have sufficient information.

- tr_4hXCGvpWpz
- tr_MMcQ2bAHpR (we use the webhook URL to create order)

Thanks

**Comment by justelis22** [comment]
Hello there @alohaoanna!

Our developer will look into it and we will let you know as soon as we have any news.

Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hello there @alohaoanna!

Could you please share the BO+FTP+SSH credentials to [support@invertus.eu](mailto:support@invertus.eu), so that our team could check and investigate the issue further.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hello there, @alohaoanna!

We have sent you a reply via email, please let us know if the solution helps!

Best regards,
Invertus support team.

**Comment by justelis22** [comment]
Hi @alohaoanna,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions or if the issue occurs again!

Best regards,
Invertus Support team
