### ISSUE TITLE
Mollie email contains the wrong description

### ISSUE THREAD

**Issue by AaronTajriba** [mollie/PrestaShop1.7#548]
### Expected behavior
The email from Mollie contains the value witch is villed in the prestashop backoffice. This should be the same as in the Mollie Backoffice

### Actual behavior
It displays the mol_XXXXX not the value send by prestashop.

### Steps to reproduce the behavior
create and pay an order in LIVE mode

### Environment
* PrestaShop version: 1.7.6.8 
* Mollie module version: 5.0.1 
* PHP version: 7.3

**Comment by loonas** [comment]
Hi @AaronTajriba! Hope that you are doing well.
Thank you for reaching out to us regarding this issue.

We have tried out the steps mentioned to reproduce the behavior, and we have received the email with ORDXXXXX instead of the mol_XXXXX.

In this case, in order to resolve the issue, could you share your BO+FTP credentials to support@invertus.eu? Additionally, any extra information would help, such as screenshots.

Looking forward to your reply!

Best regards,
Invertus Support team
