### ISSUE TITLE
Order_id not set Klarnapaylater order

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop1.7#564]
### Expected behavior
Order_id set in ps_mollie_payments (orders with payment method Ideal or creditcard order_id is set)

### Actual behavior
order_id is empty in ps_mollie_payments (attached screenshot)

If order_id is not set in database it's not possible to start klarna payment automatically.

### Steps to reproduce the behavior
Produce an order with Klarna using frontoffice of Webshop.

### Environment
* PrestaShop version: 1.7.
* Mollie module version: latest version
* PHP version: 7.2
![klarna_order_id](https://user-images.githubusercontent.com/1645341/164294667-ac7898c2-4fda-4e38-b96f-c9ea680f1aeb.png)

**Comment by justelis22** [comment]
Hello there, @basemedia!

Could you please clarify whether the order made with Klarna is finished when you see the NULL value or is it just created and unpaid? As order_id is set when the order is created after payment is finished. If you create a payment but don't finish it then the order is not created and so there is no order_id.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by basemedia** [comment]
Goodmorning,

The order is finished correctly (the order is present in the backoffice of prestashop). The bank_status (in the table) is "open" though(screenshot). The status of the klarna order is "authorized" in the backoffice of Mollie. Maybe it has something to do with this?
![bankstatus](https://user-images.githubusercontent.com/1645341/164395911-7791aa1f-0b4c-44b3-9261-b33cb46d38a2.png)

**Comment by justelis22** [comment]
Thanks for the additional details, @basemedia!

Our developer asked if the issue is related to this one order only or if all of the orders made with Klarna are affected. Most likely the issue is related to a faulty webhook, so it would be really helpful if you could check the order history on your account at mollie.com and see if the webhook call was successful, or if any error can be seen.

To deal with the case efficiently, could you also share your BO+SSH+FTP credentials to [support@invertus.eu](mailto:support@invertus.eu), so that our developer could check the issue out from their side?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by basemedia** [comment]
It's on all klarna orders. Somehow the transaction id is not set (this was an issue before) Maybe the update of the module went wrong?

**Comment by justelis22** [comment]
Hello, @basemedia!

Without a proper investigation, it is hard to tell what could have caused the issue, in this case, we would need access to your shop via BO and SSH. This way we could investigate the issue and hopefully implement a fix.

Waiting for the details!

Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hi @basemedia,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions or when you would like to continue!

Best regards,
Invertus Support team
